# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
name: sisonkerising
description: sisonkerising website
url: mandlamag.github.io
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: SisonkeRising
    hero_description:  Jekyll theme for SisonkeRising

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: +27 78 019 0607
    emergency: 931 53 234
    email: info@sisonkerising.co.za
    address: 80 Champion Street, <br> Midrand - South Africa

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: paralex.jpeg

# Map
map:
    zoom: 17
    address: Von schroeders 273, Viña del mar, Chile
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com

# Footer
copyright: © 2016 SisonkeRising - All rights reserved

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: dist
exclude: ['assets']

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: Mandla
  email: mandla.magagula@gmail.com
  uri: mandlamag.gihub.io
  bio: 
  twitter: mandlamag

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
permalink: pretty
paginate: 10
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library and options
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

# Extending Jekyll
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

# Settings for archives
jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layouts:
    year: 'year-archive'
    month: 'month-archive'
    category: 'category-archive'
    tag: 'tag-archive'
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    category: '/category/:name/'
    tags: '/tag/:name/'
